name: Apply Templates
on:
  push:
  schedule:
    - cron: "17 4 * * *"
jobs:
  update-python-versions:
    runs-on: ubuntu-latest
    container: 
      image: "ggtools/gomplate-alpine:latest"
    steps:
      - uses: actions/checkout@v3

      - name: Apply Templates
        run: ./apply-templates.sh
        
      - name: Mark git directory as safe
        run: git config --global --add safe.directory /__w/rocky-python/rocky-python

      - name: Display Git Status
        run: git status

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          commit-message: "[create-pull-request] Apply templates from official images"
