name: Ecr Upload
on:
  push:
  # schedule:
  #   - cron: "17 4 * * *"
jobs:
  upload-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Pull Push
        run: |
          docker pull ggtools/rocky-python:latest
          docker tag ggtools/rocky-python:latest public.ecr.aws/h7h4g8x7/rocky-python:latest
          docker push public.ecr.aws/h7h4g8x7/rocky-python:latest
